// Admin
export const CREATE_ADMIN = 'CREATE_ADMIN';
export const FETCH_ADMINS = 'FETCH_ADMINS';
export const UPDATE_ADMIN = 'UPDATE_ADMIN';
export const UPDATE_CURRENT_ADMIN = 'UPDATE_CURRENT_ADMIN';
export const DELETE_CURRENT_ADMIN = 'DELETE_CURRENT_ADMIN';

// Customer
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const UPDATE_CURRENT_CUSTOMER = 'UPDATE_CURRENT_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';

// Error
export const ERROR = 'ERROR';

// Menu
export const ADD_MENU_ITEM = 'ADD_MENU_ITEM';
export const DELETE_MENU_ITEM = 'DELETE_MENU_ITEM';
export const FETCH_MENU = 'FETCH_MENU';
export const UPDATE_MENU_ITEM = 'UPDATE_MENU_ITEM';

// Order
export const ADD_ORDER = 'ADD_ORDER';
export const FETCH_ORDERS = 'FETCH_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
